version: '3.8'

services:
  quotes-website:
    build: .
    container_name: quotes-website
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - PORT=3001
    restart: unless-stopped
    volumes:
      - ./logs:/usr/src/app/logs
