version: '3.8'

services:
  quotes-website:
    build: .
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - PORT=3002
    restart: unless-stopped
    networks:
      - d-nginx_default

networks:
  d-nginx_default:
    external: true
